
 
plotSmooth.custom <- function(gam2plot, counts2plot, predictedSmoothers, gene, sample.length = 100, nPoints = 100 ){

      cell.samples <- sample.equal(1:length(counts2plot[1,]), as.factor(GMM.clusters), sample.length)
          cell.samples.A <- cell.samples[cell.samples %in% grep("A", GMM.clusters)]
          cell.samples.B <- cell.samples[cell.samples %in% grep("B", GMM.clusters)]
          
         c.s.GMM.colours.A <- c(colorRampPalette(colors=cambridge.sunset[rev(c(9,8,7,6))])(7)[2:7],
              colorRampPalette(colors=cambridge.sunset[rev(c(2,1,6))])(7)[2:7]
            )[GMM.clusters][cell.samples.A]
         c.s.GMM.colours.B <- c(colorRampPalette(colors=cambridge.sunset[rev(c(9,8,7,6))])(7)[2:7],
             colorRampPalette(colors=cambridge.sunset[rev(c(2,1,6))])(7)[2:7]
            )[GMM.clusters][cell.samples.B]
    
     
         # predictedSmootherplot is a matrix generated by predictSmooth() with tidy=F
# black underlay          
          plot(range(c(gam2plot$slingshot$pseudotime.A,gam2plot$slingshot$pseudotime.B)),
            range(log(counts2plot[gene,]+1)),xlab="pseudotime", ylab="log (DCA counts + 1)", pch=NA
          )
          points(c(gam2plot$slingshot$pseudotime.A[cell.samples.A],gam2plot$slingshot$pseudotime.B[cell.samples.B]),
            log(c(counts2plot[gene,cell.samples.A],counts2plot[gene,cell.samples.B])+1), cex=1.3
          )

# A
          points(gam2plot$slingshot$pseudotime.A[cell.samples.A],
            log(counts2plot[gene,cell.samples.A]+1), 
            col=c.s.GMM.colours.A
          )
          
# B        
          points(gam2plot$slingshot$pseudotime.B[cell.samples.B],
            log(counts2plot[gene,cell.samples.B]+1),
            col=c.s.GMM.colours.B
          )  
          
          
#          test.gamplot <- predictSmooth(gam2plot, gene, nPoints=nPoints)
#            lines(test.gamplot[test.gamplot[,1]==2,2], log(test.gamplot[test.gamplot[,1]==2,4]+1), col="white", lwd=4)
#            lines(test.gamplot[test.gamplot[,1]==2,2], log(test.gamplot[test.gamplot[,1]==2,4]+1), col=cambridge.sunset[1], lwd=2)
#            lines(test.gamplot[test.gamplot[,1]==1,2], log(test.gamplot[test.gamplot[,1]==1,4]+1), col="white", lwd=4)
#            lines(test.gamplot[test.gamplot[,1]==1,2], log(test.gamplot[test.gamplot[,1]==1,4]+1), col=cambridge.sunset[8], lwd=2)        
        lines(seq(0,1,length=nPoints)*max(gam2plot$slingshot$pseudotime.A), 
              log(predictedSmoothers[gene,grep("lineage1",colnames(predictedSmoothers))]+1), 
              col="white", lwd=4)
        lines(seq(0,1,length=nPoints)*max(gam2plot$slingshot$pseudotime.A), 
              log(predictedSmoothers[gene,grep("lineage1",colnames(predictedSmoothers))]+1), 
              col=cambridge.sunset[8], lwd=2)
        lines(seq(0,1,length=nPoints)*max(gam2plot$slingshot$pseudotime.B), 
              log(predictedSmoothers[gene,grep("lineage2",colnames(predictedSmoothers))]+1), 
              col="white", lwd=4)
        lines(seq(0,1,length=nPoints)*max(gam2plot$slingshot$pseudotime.B), 
              log(predictedSmoothers[gene,grep("lineage2",colnames(predictedSmoothers))]+1), 
              col=cambridge.sunset[1], lwd=2)
                
         mtext(gene, 3)
        }
        
        
        
        
        
